stages:
  - syntax
  - lint
  - build
  - test
  - coverage

rust_fmt:
  stage: syntax
  script:
    - rustup install nightly
    - cargo +nightly fmt --all -- --check
  image: rust:latest

rust_clippy:
  stage: lint
  script:
    - cargo +stable clippy --all-features
  image: rust:latest

rust_build:
  stage: build
  script:
    - cargo build --verbose --target x86_64-unknown-linux-gnu
  image: rust:latest

rust_test:
  stage: test
  script:
    - cargo test --verbose --all-features --target x86_64-unknown-linux-gnu
  image: rust:latest

rust-coverage:
  stage: coverage
  script:
    - rustup show
    - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
    - ./grcov --version
    - export CARGO_INCREMENTAL=0
    - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
    - export RUSTDOCFLAGS="-Cpanic=abort"
    - rustup install nightly
    - cargo +nightly build
    - cargo +nightly test
    - ./grcov ./target/debug/ -s . --commit-sha="${ CI_COMMIT_SHA }" --llvm --branch --ignore-not-existing --ignore="/*" --ignore="*_tests.rs" --ignore="benches/*" -t html -o ./target/debug/coverage
    - cat ./target/debug/coverage/index.html
  image: rust:latest
