image: rikorose/gcc-cmake:latest

before_script:
  - apt-get update && apt-get -y install radare2
  - wget https://github.com/google/googletest/archive/release-1.8.1.tar.gz &&
    tar xzf release-1.8.1.tar.gz && cd googletest-release-1.8.1/ && mkdir build && cd build && cmake .. && make install && cd ../..

stages:
  - build
  - test

x86_build:
  stage: build
  script:
    - mkdir build && cd build && cmake .. && make
  tags:
    - x86_64

x86_test:
  stage: test
  script:
    - mkdir build && cd build && cmake .. && make runTests && make test
  tags:
    - x86_64
